server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

#security:
#  basic:
#    enabled: false
#    path: /admin
#  user:
#    name: admin
#    password: password